sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.6.3
env:
  - SCORPIO_API_DESCRIPTION_FORMAT=rest_description
  - SCORPIO_API_DESCRIPTION_FORMAT=openapi2
  - SCORPIO_API_DESCRIPTION_FORMAT=openapi3
script: bundle exec rake test
