sudo: false
language: ruby
rvm:
  - 2.1.10
  - 2.6.3
env:
  - SCORPIO_API_DESCRIPTION_FORMAT=rest_description
  - SCORPIO_API_DESCRIPTION_FORMAT=openapi2
  - SCORPIO_API_DESCRIPTION_FORMAT=openapi3
script: rake test
